linters:
  enable-all: true
  disable:
    - exhaustruct
    - forbidigo
    - golint
    - interfacer
    - maligned
    - wsl
    - scopelint
    - gochecknoinits
    - exhaustivestruct
    - testpackage
    - paralleltest
    - gochecknoglobals
    - varnamelen
linters-settings:
  lll:
    line-length: 100
    tab-width: 4
  misspell:
    locale: US
